
#ifndef __SCSI_DEFS_H
#define __SCSI_DEFS_H

enum SCSI_DEVICE_TYPE {
	SCSI_DEVICE_TYPE_DISK,		/* 00 */
	SCSI_DEVICE_TYPE_TAPE,		/* 01 */
	SCSI_DEVICE_TYPE_PRINTER,	/* 02 */
	SCSI_DEVICE_TYPE_PROCESSOR,	/* 03 */
	SCSI_DEVICE_TYPE_WORM,		/* 04 */
	SCSI_DEVICE_TYPE_CD,		/* 05 */
	SCSI_DEVICE_TYPE_OPTICAL,	/* 06 */
	SCSI_DEVICE_TYPE_CHANGER,	/* 07 */
	SCSI_DEVICE_TYPE_ARRAY,		/* 08 */
	SCSI_DEVICE_TYPE_ENCLOSURE,	/* 09 */
	SCSI_DEVICE_TYPE_SIMPLE,	/* 10 */
	SCSI_DEVICE_TYPE_READER,	/* 11 */
	SCSI_DEVICE_TYPE_AUTOMATION,	/* 12 */
	SCSI_DEVICE_TYPE_OBJECT,	/* 13 */

	SCSI_DEVICE_TYPE_MAX=13		/* 13 */
};

#endif
